### ISSUE TITLE
Exp needs a review

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/apd#14]

**Comment by eisenstatdavid** [comment]
Looks good with two nits:

1. https://github.com/cockroachdb/apd/blob/78ac5e971cb201988eeff99f2385053731f29196/context.go#L756 should read `Quo`, not `QuoInteger`.

2. https://github.com/cockroachdb/apd/blob/78ac5e971cb201988eeff99f2385053731f29196/context.go#L767 Doing the Stage 3 calculation in floating-point without directed rounding makes me a little nervous, but I think that there's enough slack elsewhere in the analysis that, if `log10` is correct to 1 ulp, then we're fine.

An easy way around the precision assertion is to just increase the working precision -- is this infeasible for some reason? The root cause seems to be that raising `sum` to the `k`th power creates a demanding accuracy requirement on `sum`, so I don't know that this limitation can be easily removed.
