### ISSUE TITLE
CmpTotal Bug

### ISSUE THREAD

**Issue by dhui** [cockroachdb/apd#65]
`CmpTotal()` does not properly compare equivalent `Decimal` values when the coefficient and exponent representations differ

Example:
---------
```go
package main

import (
    "github.com/cockroachdb/apd"
    "log"
)

func main() {
    a := apd.New(10, 0)
    b := apd.New(1, 1)
    log.Println(a)             // prints 10
    log.Println(b)             // prints 1E+1
    log.Println(a.CmpTotal(b)) // prints -1
    log.Println(a.Cmp(b))      // prints 0
    log.Println(b.CmpTotal(a)) // prints 1
    log.Println(b.Cmp(a))      // prints 0
}
```

**Comment by mjibson** [comment]
This is working as intended (see the specification at http://speleotrove.com/decimal/damisc.html#refcotot), point number 2:

> If two representations have the same numerical value then the exponent is taken into account; larger (more positive) exponents are higher in the ordering.

I do think that the documentation of Cmp and CmpTotal needs to be improved to discuss this, though, because that's clearly not obvious to users.

I've opened #66 to address the docs issue.

**Comment by dhui** [comment]
Thanks for the clarification! Time to update all of my code to use `Cmp()` instead of `CmpTotal()`!
